name: Update

on:
  label:
    types:
      - created # for test
  schedule:
      - cron: '0 1 * * *' # 09:00 Beijing time everyday
  workflow_dispatch: # 手动触发

permissions:
  contents: write
  issues: write 

jobs:
  update_daily_papers:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update papers
      run: |
        python main.py

    - name: Commit and push changes
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: '✏️ Update papers automatically.'
        force-add: 'true'
        files: README.md .github/ISSUE_TEMPLATE.md
        name: pstAmbition
        email: 2583009344@qq.com

    - name: Create an issue to notify
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
